.TH HARCH 1 local
.SH NAME
harch \- determine machine architecture for nhc98 and hmake
.SH SYNOPSIS
.B harch
.SH DESCRIPTION
.I harch
is a simple script to determine a canonical name for
your machine architecture in a format that the
.I nhc98
compiler and
.I hmake
compilation manager will recognise.

.SH FILES
.TP 25
.B /usr/local/bin/harch

.SH "SEE ALSO"
hmake(1), nhc98(1)
