include Makefile.inc

THISLIB	= Bit
SEARCH	=
EXTRA_H_FLAGS	=
EXTRA_C_FLAGS	=

SRCS	=  # None, just the main library

# Here are the main rules.
include ../Makefile.common


# Here are the dependencies.

