include Makefile.inc

THISLIB	= IOExtras
SEARCH	= -P$(LOW) -P../PreludeIO -P../Array -P../IO

SRCS	= \
	FixIO.hs PerformGC.hs UnsafePtrEq.hs \
	DIOArray.hs BoundsIOArray.hs FreezeIOArray.hs NewIOArray.hs \
	ReadIOArray.hs WriteIOArray.hs \
	DIORef.hs NewIORef.hs ReadIORef.hs WriteIORef.hs \
	ExcludeFinalisers.hs HPutGetBuf.hs


# Here are the main rules.
include ../Makefile.common


# Here are the dependencies.

