#include <stdlib.h>
#include <stdio.h>
#include <errno.h>

#ifdef E2BIG
#define CCONST_E2BIG E2BIG
#else
#define CCONST_E2BIG (-1)
#endif

#ifdef EACCES
#define CCONST_EACCES EACCES
#else
#define CCONST_EACCES (-1)
#endif

#ifdef EADDRINUSE
#define CCONST_EADDRINUSE EADDRINUSE
#else
#define CCONST_EADDRINUSE (-1)
#endif

#ifdef EADDRNOTAVAIL
#define CCONST_EADDRNOTAVAIL EADDRNOTAVAIL
#else
#define CCONST_EADDRNOTAVAIL (-1)
#endif

#ifdef EADV
#define CCONST_EADV EADV
#else
#define CCONST_EADV (-1)
#endif

#ifdef EAFNOSUPPORT
#define CCONST_EAFNOSUPPORT EAFNOSUPPORT
#else
#define CCONST_EAFNOSUPPORT (-1)
#endif

#ifdef EAGAIN
#define CCONST_EAGAIN EAGAIN
#else
#define CCONST_EAGAIN (-1)
#endif

#ifdef EALREADY
#define CCONST_EALREADY EALREADY
#else
#define CCONST_EALREADY (-1)
#endif

#ifdef EBADF
#define CCONST_EBADF EBADF
#else
#define CCONST_EBADF (-1)
#endif

#ifdef EBADMSG
#define CCONST_EBADMSG EBADMSG
#else
#define CCONST_EBADMSG (-1)
#endif

#ifdef EBADRPC
#define CCONST_EBADRPC EBADRPC
#else
#define CCONST_EBADRPC (-1)
#endif

#ifdef EBUSY
#define CCONST_EBUSY EBUSY
#else
#define CCONST_EBUSY (-1)
#endif

#ifdef ECHILD
#define CCONST_ECHILD ECHILD
#else
#define CCONST_ECHILD (-1)
#endif

#ifdef ECOMM
#define CCONST_ECOMM ECOMM
#else
#define CCONST_ECOMM (-1)
#endif

#ifdef ECONNABORTED
#define CCONST_ECONNABORTED ECONNABORTED
#else
#define CCONST_ECONNABORTED (-1)
#endif

#ifdef ECONNREFUSED
#define CCONST_ECONNREFUSED ECONNREFUSED
#else
#define CCONST_ECONNREFUSED (-1)
#endif

#ifdef ECONNRESET
#define CCONST_ECONNRESET ECONNRESET
#else
#define CCONST_ECONNRESET (-1)
#endif

#ifdef EDEADLK
#define CCONST_EDEADLK EDEADLK
#else
#define CCONST_EDEADLK (-1)
#endif

#ifdef EDESTADDRREQ
#define CCONST_EDESTADDRREQ EDESTADDRREQ
#else
#define CCONST_EDESTADDRREQ (-1)
#endif

#ifdef EDIRTY
#define CCONST_EDIRTY EDIRTY
#else
#define CCONST_EDIRTY (-1)
#endif

#ifdef EDOM
#define CCONST_EDOM EDOM
#else
#define CCONST_EDOM (-1)
#endif

#ifdef EDQUOT
#define CCONST_EDQUOT EDQUOT
#else
#define CCONST_EDQUOT (-1)
#endif

#ifdef EEXIST
#define CCONST_EEXIST EEXIST
#else
#define CCONST_EEXIST (-1)
#endif

#ifdef EFAULT
#define CCONST_EFAULT EFAULT
#else
#define CCONST_EFAULT (-1)
#endif

#ifdef EFBIG
#define CCONST_EFBIG EFBIG
#else
#define CCONST_EFBIG (-1)
#endif

#ifdef EFTYPE
#define CCONST_EFTYPE EFTYPE
#else
#define CCONST_EFTYPE (-1)
#endif

#ifdef EHOSTDOWN
#define CCONST_EHOSTDOWN EHOSTDOWN
#else
#define CCONST_EHOSTDOWN (-1)
#endif

#ifdef EHOSTUNREACH
#define CCONST_EHOSTUNREACH EHOSTUNREACH
#else
#define CCONST_EHOSTUNREACH (-1)
#endif

#ifdef EIDRM
#define CCONST_EIDRM EIDRM
#else
#define CCONST_EIDRM (-1)
#endif

#ifdef EILSEQ
#define CCONST_EILSEQ EILSEQ
#else
#define CCONST_EILSEQ (-1)
#endif

#ifdef EINPROGRESS
#define CCONST_EINPROGRESS EINPROGRESS
#else
#define CCONST_EINPROGRESS (-1)
#endif

#ifdef EINTR
#define CCONST_EINTR EINTR
#else
#define CCONST_EINTR (-1)
#endif

#ifdef EINVAL
#define CCONST_EINVAL EINVAL
#else
#define CCONST_EINVAL (-1)
#endif

#ifdef EIO
#define CCONST_EIO EIO
#else
#define CCONST_EIO (-1)
#endif

#ifdef EISCONN
#define CCONST_EISCONN EISCONN
#else
#define CCONST_EISCONN (-1)
#endif

#ifdef EISDIR
#define CCONST_EISDIR EISDIR
#else
#define CCONST_EISDIR (-1)
#endif

#ifdef ELOOP
#define CCONST_ELOOP ELOOP
#else
#define CCONST_ELOOP (-1)
#endif

#ifdef EMFILE
#define CCONST_EMFILE EMFILE
#else
#define CCONST_EMFILE (-1)
#endif

#ifdef EMLINK
#define CCONST_EMLINK EMLINK
#else
#define CCONST_EMLINK (-1)
#endif

#ifdef EMSGSIZE
#define CCONST_EMSGSIZE EMSGSIZE
#else
#define CCONST_EMSGSIZE (-1)
#endif

#ifdef EMULTIHOP
#define CCONST_EMULTIHOP EMULTIHOP
#else
#define CCONST_EMULTIHOP (-1)
#endif

#ifdef ENAMETOOLONG
#define CCONST_ENAMETOOLONG ENAMETOOLONG
#else
#define CCONST_ENAMETOOLONG (-1)
#endif

#ifdef ENETDOWN
#define CCONST_ENETDOWN ENETDOWN
#else
#define CCONST_ENETDOWN (-1)
#endif

#ifdef ENETRESET
#define CCONST_ENETRESET ENETRESET
#else
#define CCONST_ENETRESET (-1)
#endif

#ifdef ENETUNREACH
#define CCONST_ENETUNREACH ENETUNREACH
#else
#define CCONST_ENETUNREACH (-1)
#endif

#ifdef ENFILE
#define CCONST_ENFILE ENFILE
#else
#define CCONST_ENFILE (-1)
#endif

#ifdef ENOBUFS
#define CCONST_ENOBUFS ENOBUFS
#else
#define CCONST_ENOBUFS (-1)
#endif

#ifdef ENODATA
#define CCONST_ENODATA ENODATA
#else
#define CCONST_ENODATA (-1)
#endif

#ifdef ENODEV
#define CCONST_ENODEV ENODEV
#else
#define CCONST_ENODEV (-1)
#endif

#ifdef ENOENT
#define CCONST_ENOENT ENOENT
#else
#define CCONST_ENOENT (-1)
#endif

#ifdef ENOEXEC
#define CCONST_ENOEXEC ENOEXEC
#else
#define CCONST_ENOEXEC (-1)
#endif

#ifdef ENOLCK
#define CCONST_ENOLCK ENOLCK
#else
#define CCONST_ENOLCK (-1)
#endif

#ifdef ENOLINK
#define CCONST_ENOLINK ENOLINK
#else
#define CCONST_ENOLINK (-1)
#endif

#ifdef ENOMEM
#define CCONST_ENOMEM ENOMEM
#else
#define CCONST_ENOMEM (-1)
#endif

#ifdef ENOMSG
#define CCONST_ENOMSG ENOMSG
#else
#define CCONST_ENOMSG (-1)
#endif

#ifdef ENONET
#define CCONST_ENONET ENONET
#else
#define CCONST_ENONET (-1)
#endif

#ifdef ENOPROTOOPT
#define CCONST_ENOPROTOOPT ENOPROTOOPT
#else
#define CCONST_ENOPROTOOPT (-1)
#endif

#ifdef ENOSPC
#define CCONST_ENOSPC ENOSPC
#else
#define CCONST_ENOSPC (-1)
#endif

#ifdef ENOSR
#define CCONST_ENOSR ENOSR
#else
#define CCONST_ENOSR (-1)
#endif

#ifdef ENOSTR
#define CCONST_ENOSTR ENOSTR
#else
#define CCONST_ENOSTR (-1)
#endif

#ifdef ENOSYS
#define CCONST_ENOSYS ENOSYS
#else
#define CCONST_ENOSYS (-1)
#endif

#ifdef ENOTBLK
#define CCONST_ENOTBLK ENOTBLK
#else
#define CCONST_ENOTBLK (-1)
#endif

#ifdef ENOTCONN
#define CCONST_ENOTCONN ENOTCONN
#else
#define CCONST_ENOTCONN (-1)
#endif

#ifdef ENOTDIR
#define CCONST_ENOTDIR ENOTDIR
#else
#define CCONST_ENOTDIR (-1)
#endif

#ifdef ENOTEMPTY
#define CCONST_ENOTEMPTY ENOTEMPTY
#else
#define CCONST_ENOTEMPTY (-1)
#endif

#ifdef ENOTSOCK
#define CCONST_ENOTSOCK ENOTSOCK
#else
#define CCONST_ENOTSOCK (-1)
#endif

#ifdef ENOTTY
#define CCONST_ENOTTY ENOTTY
#else
#define CCONST_ENOTTY (-1)
#endif

#ifdef ENXIO
#define CCONST_ENXIO ENXIO
#else
#define CCONST_ENXIO (-1)
#endif

#ifdef EOPNOTSUPP
#define CCONST_EOPNOTSUPP EOPNOTSUPP
#else
#define CCONST_EOPNOTSUPP (-1)
#endif

#ifdef EPERM
#define CCONST_EPERM EPERM
#else
#define CCONST_EPERM (-1)
#endif

#ifdef EPFNOSUPPORT
#define CCONST_EPFNOSUPPORT EPFNOSUPPORT
#else
#define CCONST_EPFNOSUPPORT (-1)
#endif

#ifdef EPIPE
#define CCONST_EPIPE EPIPE
#else
#define CCONST_EPIPE (-1)
#endif

#ifdef EPROCLIM
#define CCONST_EPROCLIM EPROCLIM
#else
#define CCONST_EPROCLIM (-1)
#endif

#ifdef EPROCUNAVAIL
#define CCONST_EPROCUNAVAIL EPROCUNAVAIL
#else
#define CCONST_EPROCUNAVAIL (-1)
#endif

#ifdef EPROGMISMATCH
#define CCONST_EPROGMISMATCH EPROGMISMATCH
#else
#define CCONST_EPROGMISMATCH (-1)
#endif

#ifdef EPROGUNAVAIL
#define CCONST_EPROGUNAVAIL EPROGUNAVAIL
#else
#define CCONST_EPROGUNAVAIL (-1)
#endif

#ifdef EPROTO
#define CCONST_EPROTO EPROTO
#else
#define CCONST_EPROTO (-1)
#endif

#ifdef EPROTONOSUPPORT
#define CCONST_EPROTONOSUPPORT EPROTONOSUPPORT
#else
#define CCONST_EPROTONOSUPPORT (-1)
#endif

#ifdef EPROTOTYPE
#define CCONST_EPROTOTYPE EPROTOTYPE
#else
#define CCONST_EPROTOTYPE (-1)
#endif

#ifdef ERANGE
#define CCONST_ERANGE ERANGE
#else
#define CCONST_ERANGE (-1)
#endif

#ifdef EREMCHG
#define CCONST_EREMCHG EREMCHG
#else
#define CCONST_EREMCHG (-1)
#endif

#ifdef EREMOTE
#define CCONST_EREMOTE EREMOTE
#else
#define CCONST_EREMOTE (-1)
#endif

#ifdef EROFS
#define CCONST_EROFS EROFS
#else
#define CCONST_EROFS (-1)
#endif

#ifdef ERPCMISMATCH
#define CCONST_ERPCMISMATCH ERPCMISMATCH
#else
#define CCONST_ERPCMISMATCH (-1)
#endif

#ifdef ERREMOTE
#define CCONST_ERREMOTE ERREMOTE
#else
#define CCONST_ERREMOTE (-1)
#endif

#ifdef ESHUTDOWN
#define CCONST_ESHUTDOWN ESHUTDOWN
#else
#define CCONST_ESHUTDOWN (-1)
#endif

#ifdef ESOCKTNOSUPPORT
#define CCONST_ESOCKTNOSUPPORT ESOCKTNOSUPPORT
#else
#define CCONST_ESOCKTNOSUPPORT (-1)
#endif

#ifdef ESPIPE
#define CCONST_ESPIPE ESPIPE
#else
#define CCONST_ESPIPE (-1)
#endif

#ifdef ESRCH
#define CCONST_ESRCH ESRCH
#else
#define CCONST_ESRCH (-1)
#endif

#ifdef ESRMNT
#define CCONST_ESRMNT ESRMNT
#else
#define CCONST_ESRMNT (-1)
#endif

#ifdef ESTALE
#define CCONST_ESTALE ESTALE
#else
#define CCONST_ESTALE (-1)
#endif

#ifdef ETIME
#define CCONST_ETIME ETIME
#else
#define CCONST_ETIME (-1)
#endif

#ifdef ETIMEDOUT
#define CCONST_ETIMEDOUT ETIMEDOUT
#else
#define CCONST_ETIMEDOUT (-1)
#endif

#ifdef ETOOMANYREFS
#define CCONST_ETOOMANYREFS ETOOMANYREFS
#else
#define CCONST_ETOOMANYREFS (-1)
#endif

#ifdef ETXTBSY
#define CCONST_ETXTBSY ETXTBSY
#else
#define CCONST_ETXTBSY (-1)
#endif

#ifdef EUSERS
#define CCONST_EUSERS EUSERS
#else
#define CCONST_EUSERS (-1)
#endif

#ifdef EWOULDBLOCK
#define CCONST_EWOULDBLOCK EWOULDBLOCK
#else
#define CCONST_EWOULDBLOCK (-1)
#endif

#ifdef EXDEV
#define CCONST_EXDEV EXDEV
#else
#define CCONST_EXDEV (-1)
#endif

#define drop(name,value)	printf("%-16s = Errno (%d)\n",name,value);
main () {
  drop("e2BIG",CCONST_E2BIG);
  drop("eACCES",CCONST_EACCES);
  drop("eADDRINUSE",CCONST_EADDRINUSE);
  drop("eADDRNOTAVAIL",CCONST_EADDRNOTAVAIL);
  drop("eADV",CCONST_EADV);
  drop("eAFNOSUPPORT",CCONST_EAFNOSUPPORT);
  drop("eAGAIN",CCONST_EAGAIN);
  drop("eALREADY",CCONST_EALREADY);
  drop("eBADF",CCONST_EBADF);
  drop("eBADMSG",CCONST_EBADMSG);
  drop("eBADRPC",CCONST_EBADRPC);
  drop("eBUSY",CCONST_EBUSY);
  drop("eCHILD",CCONST_ECHILD);
  drop("eCOMM",CCONST_ECOMM);
  drop("eCONNABORTED",CCONST_ECONNABORTED);
  drop("eCONNREFUSED",CCONST_ECONNREFUSED);
  drop("eCONNRESET",CCONST_ECONNRESET);
  drop("eDEADLK",CCONST_EDEADLK);
  drop("eDESTADDRREQ",CCONST_EDESTADDRREQ);
  drop("eDIRTY",CCONST_EDIRTY);
  drop("eDOM",CCONST_EDOM);
  drop("eDQUOT",CCONST_EDQUOT);
  drop("eEXIST",CCONST_EEXIST);
  drop("eFAULT",CCONST_EFAULT);
  drop("eFBIG",CCONST_EFBIG);
  drop("eFTYPE",CCONST_EFTYPE);
  drop("eHOSTDOWN",CCONST_EHOSTDOWN);
  drop("eHOSTUNREACH",CCONST_EHOSTUNREACH);
  drop("eIDRM",CCONST_EIDRM);
  drop("eILSEQ",CCONST_EILSEQ);
  drop("eINPROGRESS",CCONST_EINPROGRESS);
  drop("eINTR",CCONST_EINTR);
  drop("eINVAL",CCONST_EINVAL);
  drop("eIO",CCONST_EIO);
  drop("eISCONN",CCONST_EISCONN);
  drop("eISDIR",CCONST_EISDIR);
  drop("eLOOP",CCONST_ELOOP);
  drop("eMFILE",CCONST_EMFILE);
  drop("eMLINK",CCONST_EMLINK);
  drop("eMSGSIZE",CCONST_EMSGSIZE);
  drop("eMULTIHOP",CCONST_EMULTIHOP);
  drop("eNAMETOOLONG",CCONST_ENAMETOOLONG);
  drop("eNETDOWN",CCONST_ENETDOWN);
  drop("eNETRESET",CCONST_ENETRESET);
  drop("eNETUNREACH",CCONST_ENETUNREACH);
  drop("eNFILE",CCONST_ENFILE);
  drop("eNOBUFS",CCONST_ENOBUFS);
  drop("eNODATA",CCONST_ENODATA);
  drop("eNODEV",CCONST_ENODEV);
  drop("eNOENT",CCONST_ENOENT);
  drop("eNOEXEC",CCONST_ENOEXEC);
  drop("eNOLCK",CCONST_ENOLCK);
  drop("eNOLINK",CCONST_ENOLINK);
  drop("eNOMEM",CCONST_ENOMEM);
  drop("eNOMSG",CCONST_ENOMSG);
  drop("eNONET",CCONST_ENONET);
  drop("eNOPROTOOPT",CCONST_ENOPROTOOPT);
  drop("eNOSPC",CCONST_ENOSPC);
  drop("eNOSR",CCONST_ENOSR);
  drop("eNOSTR",CCONST_ENOSTR);
  drop("eNOSYS",CCONST_ENOSYS);
  drop("eNOTBLK",CCONST_ENOTBLK);
  drop("eNOTCONN",CCONST_ENOTCONN);
  drop("eNOTDIR",CCONST_ENOTDIR);
  drop("eNOTEMPTY",CCONST_ENOTEMPTY);
  drop("eNOTSOCK",CCONST_ENOTSOCK);
  drop("eNOTTY",CCONST_ENOTTY);
  drop("eNXIO",CCONST_ENXIO);
  drop("eOPNOTSUPP",CCONST_EOPNOTSUPP);
  drop("ePERM",CCONST_EPERM);
  drop("ePFNOSUPPORT",CCONST_EPFNOSUPPORT);
  drop("ePIPE",CCONST_EPIPE);
  drop("ePROCLIM",CCONST_EPROCLIM);
  drop("ePROCUNAVAIL",CCONST_EPROCUNAVAIL);
  drop("ePROGMISMATCH",CCONST_EPROGMISMATCH);
  drop("ePROGUNAVAIL",CCONST_EPROGUNAVAIL);
  drop("ePROTO",CCONST_EPROTO);
  drop("ePROTONOSUPPORT",CCONST_EPROTONOSUPPORT);
  drop("ePROTOTYPE",CCONST_EPROTOTYPE);
  drop("eRANGE",CCONST_ERANGE);
  drop("eREMCHG",CCONST_EREMCHG);
  drop("eREMOTE",CCONST_EREMOTE);
  drop("eROFS",CCONST_EROFS);
  drop("eRPCMISMATCH",CCONST_ERPCMISMATCH);
  drop("eRREMOTE",CCONST_ERREMOTE);
  drop("eSHUTDOWN",CCONST_ESHUTDOWN);
  drop("eSOCKTNOSUPPORT",CCONST_ESOCKTNOSUPPORT);
  drop("eSPIPE",CCONST_ESPIPE);
  drop("eSRCH",CCONST_ESRCH);
  drop("eSRMNT",CCONST_ESRMNT);
  drop("eSTALE",CCONST_ESTALE);
  drop("eTIME",CCONST_ETIME);
  drop("eTIMEDOUT",CCONST_ETIMEDOUT);
  drop("eTOOMANYREFS",CCONST_ETOOMANYREFS);
  drop("eTXTBSY",CCONST_ETXTBSY);
  drop("eUSERS",CCONST_EUSERS);
  drop("eWOULDBLOCK",CCONST_EWOULDBLOCK);
  drop("eXDEV",CCONST_EXDEV);
  exit(0);
}
