include Makefile.inc

THISLIB	= PreludeList
SEARCH	=
EXTRA_H_FLAGS	= --prelude
EXTRA_C_FLAGS	=

SRCS	= \
	Append.hs      Elem.hs        Lines.hs       Replicate.hs  \
	Lookup.hs      Reverse.hs     Unlines.hs     Map.hs \
	All.hs         Foldl.hs       Scanl.hs       Unwords.hs	\
	And.hs         Foldl1.hs      Maximum.hs     Scanl1.hs \
	Any.hs         Foldr.hs       Minimum.hs     Scanr.hs  \
        Unzip.hs       Unzip3.hs      ZipWith.hs     ZipWith3.hs 	\
	Break.hs       Foldr1.hs      NotElem.hs     Scanr1.hs \
	Head.hs        Span.hs        Zip.hs         Concat.hs \
	ConcatMap.hs   Index.hs       Null.hs        SplitAt.hs \
	Cycle.hs       Init.hs        Or.hs          Sum.hs \
	Iterate.hs     Tail.hs        Zip3.hs    Words.hs 	\
	Drop.hs        Last.hs        Product.hs     Take.hs \
	DropWhile.hs   Length.hs      Repeat.hs      TakeWhile.hs \
        Filter.hs


# Here are the main rules.
include ../Makefile.common


# Here are the dependencies.
