#ifndef _BYTECODE_H
#define _BYTECODE_H

/* This file defines the bytecodes emitted by the compiler.
 * It is used by  src/runtime/Kernel/mutator.c
 * and also by every .hc file generated by the compiler.
 *
 * We define the bytecodes as an enumeration type (rather than just a
 * standard sequence of #defines) in order to take advantage of the gcc
 * compiler extension for computed goto labels, which wins us about 25%
 * speed increase in the mutator.
 */

#include "newbytecode.h"

#define ins(x)	x
typedef enum { INSTRUCTION_LIST } Instr_t;
#undef ins

#endif
