include Makefile.inc

THISLIB	= Monad
SEARCH	=

SRCS	= \
        LiftM.hs    LiftM2.hs         LiftM3.hs     LiftM4.hs     LiftM5.hs \
        Ap.hs       CMonadPlus.hs     FilterM.hs \
	Join.hs     When.hs           Unless.hs \
        ZipWithM.hs FoldM.hs          MapAndUnzipM.hs \
        Msum.hs     ZipWithM_.hs      Guard.hs \
        MonadPlus_List.hs MonadPlus_Maybe.hs

# Here are the main rules.
include ../Makefile.common

# Here are the dependencies.
