include Makefile.inc

THISLIB	= CPUTime
SEARCH	=
EXTRA_H_FLAGS	=
EXTRA_C_FLAGS	=

SRCS	= CpuTimePrecision.hs GetCPUTime.gc

# Here are the main rules.
include ../Makefile.common

# Here are the dependencies.
